In [2]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [3]:
data=sns.load_dataset('iris')

In [4]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
x=data.iloc[:,0:4]
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
y=data.iloc[:,-1]
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [8]:
encoder=OneHotEncoder(sparse_output=False)

In [13]:
# Pass it as a DataFrame to keep the 2D shape automatically
yencode = encoder.fit_transform(data[['species']])

# Optional: To make it explicit, look at the encoded categories
Y = pd.DataFrame(yencode, columns=encoder.get_feature_names_out(['species']))
Y.sample(10)

     species_setosa  species_versicolor  species_virginica
50              0.0                 1.0                0.0
112             0.0                 0.0                1.0
93              0.0                 1.0                0.0
145             0.0                 0.0                1.0
58              0.0                 1.0                0.0
57              0.0                 1.0                0.0
106             0.0                 0.0                1.0
49              1.0                 0.0                0.0
98              0.0                 1.0                0.0
90              0.0                 1.0                0.0

In [14]:
scaler=StandardScaler()

In [ ]:
X_scaled=