# CSV DATA WORKING

In [1]:
import pandas as pd

## FROM LOCAL MACHINE

In [24]:
# from loacal machine 

path='D:\data scinece lab projects\working on CSV\housing.csv'
data=pd.read_csv(path)

In [25]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

## DATA TO CSV

In [26]:
import numpy as np

# Creating a fake dataset
data1 = {
    'Student_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Math_Score': [85, np.nan, 78, 92, np.nan, 88],
    'Science_Score': [90, 82, 85, 77, 95, 89],
    'Attendance': ['95%', '80%', '75%', '90%', '60%', '85%'],
    'Status': ['Pass', 'Pass', 'Pass', 'Pass', 'Fail', 'Pass']
}


df_csv_in=pd.DataFrame(data1)

In [5]:
df_csv_in

   Student_ID     Name  Math_Score  Science_Score Attendance Status
0         101    Alice        85.0             90        95%   Pass
1         102      Bob         NaN             82        80%   Pass
2         103  Charlie        78.0             85        75%   Pass
3         104    David        92.0             77        90%   Pass
4         105      Eva         NaN             95        60%   Fail
5         106    Frank        88.0             89        85%   Pass

In [6]:
df_csv_in.to_csv('student.csv',index=False)

In [7]:
data2=pd.read_csv('D:\data scinece lab projects\working on CSV\student.csv')

In [8]:
data2

   Student_ID     Name  Math_Score  Science_Score Attendance Status
0         101    Alice        85.0             90        95%   Pass
1         102      Bob         NaN             82        80%   Pass
2         103  Charlie        78.0             85        75%   Pass
3         104    David        92.0             77        90%   Pass
4         105      Eva         NaN             95        60%   Fail
5         106    Frank        88.0             89        85%   Pass

## FROM URL

In [9]:
URL="https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

data3=pd.read_csv(URL)


'''ADVANCE METHOD
If the pandas block by any website then it will use the request formate 

Sometimes a website might block direct access from
 Pandas (to prevent bots). In those cases, you use the requests library to "pretend" 
to be a browser, and then use io to read the text.

"import pandas as pd
import requests
import io

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

# 1. Fetch the content from the URL
response = requests.get(url)

# 2. Check if the request was successful
if response.status_status == 200:
    # 3. Use io.StringIO to convert the text content into a file-like object
    csv_data = io.StringIO(response.text)
    df = pd.read_csv(csv_data)
    
    print("Fetched via Requests:")
    print(df.info())
else:
    print("Failed to download file.")"

 '''


'''
When loading from URLs, you often encounter these three parameters:

Parameter              When to use it  
storage_options        If the URL requires an API key or User-Agent headers.
sep                    If the URL file uses tabs (\t) or semicolons (;) instead of commas.
compression            If the URL ends in .zip or .gz, Pandas can automatically unzip it if you set compression='infer'.



code 

df = pd.read_csv(
    "https://example.com/data.zip", 
    sep=',', 
    compression='zip', 
    encoding='utf-8'
)df = pd.read_csv(
    "https://example.com/data.zip", 
    sep=',', 
    compression='zip', 
    encoding='utf-8'
)



'''

'\nWhen loading from URLs, you often encounter these three parameters:\n\nParameter              When to use it  \nstorage_options        If the URL requires an API key or User-Agent headers.\nsep                    If the URL file uses tabs (\t) or semicolons (;) instead of commas.\ncompression            If the URL ends in .zip or .gz, Pandas can automatically unzip it if you set compression=\'infer\'.\n\n\n\ncode \n\ndf = pd.read_csv(\n    "https://example.com/data.zip", \n    sep=\',\', \n    compression=\'zip\', \n    encoding=\'utf-8\'\n)df = pd.read_csv(\n    "https://example.com/data.zip", \n    sep=\',\', \n    compression=\'zip\', \n    encoding=\'utf-8\'\n)\n\n\n\n'

In [10]:
data3

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### FETCH DATA TO CSV FILE CONVERSION

In [11]:
# file conversion
data3.to_csv("EXP_IRS.csv",index=False)

# DATA EXPLORATION

In [28]:
data.head()# giving a head

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
data.tail() # giving the tail

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
data.info() #giving the information about the columns

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.7 MB

In [ ]:
data.describe() # giving us the diff parameters

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
data.shape # give us the mainly col and row no

(20640, 10)

:

# LOADING TSV

## WITH NAMING TO THE UNDEFINE COLUMN

In [44]:
## how to handel  that is handel by on doing the add the "sep=/t"
## also add the r"............." it encode the string in the right formate 
## naming to the columns properly 

path=r"D:\data scinece lab projects\working on CSV\file.tsv"

data4=pd.read_csv(r"D:\data scinece lab projects\working on CSV\file.tsv",sep='\t',names=['user_id', 'item_id', 'rating', 'timestamp'])

In [45]:
data4.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

#  SAME COL NAME WITH SAME FUN CAN REPPALACE

In [56]:
# IN ABOVE THE USER ID AND THE S.NO HAVE SAME FUN 

data5=pd.read_csv("student.csv")
data5

   Student_ID     Name  Math_Score  Science_Score Attendance Status
0         101    Alice        85.0             90        95%   Pass
1         102      Bob         NaN             82        80%   Pass
2         103  Charlie        78.0             85        75%   Pass
3         104    David        92.0             77        90%   Pass
4         105      Eva         NaN             95        60%   Fail
5         106    Frank        88.0             89        85%   Pass

In [57]:
data5=pd.read_csv("student.csv",index_col='Student_ID')
data5

               Name  Math_Score  Science_Score Attendance Status
Student_ID
101           Alice        85.0             90        95%   Pass
102             Bob         NaN             82        80%   Pass
103         Charlie        78.0             85        75%   Pass
104           David        92.0             77        90%   Pass
105             Eva         NaN             95        60%   Fail
106           Frank        88.0             89        85%   Pass

# THE USING COLUMNS IN DATA SET

In [58]:
data6=pd.read_csv("student.csv",usecols=['Student_ID','Attendance','Status'])
data6

   Student_ID Attendance Status
0         101        95%   Pass
1         102        80%   Pass
2         103        75%   Pass
3         104        90%   Pass
4         105        60%   Fail
5         106        85%   Pass

# SKIPPING ROW

In [70]:
# THE COL SERIES 

row_skips=pd.read_csv("student.csv",skiprows=[1,4])
row_skips

   Student_ID     Name  Math_Score  Science_Score Attendance Status
0         102      Bob         NaN             82        80%   Pass
1         103  Charlie        78.0             85        75%   Pass
2         105      Eva         NaN             95        60%   Fail
3         106    Frank        88.0             89        85%   Pass

In [77]:

# even number load
lambda_row_skip = pd.read_csv("housing.csv", skiprows=lambda x: x %2)
lambda_row_skip

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
1,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
2,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
3,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
4,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
10315,-121.40,39.33,15.0,2655.0,493.0,1200.0,432.0,3.5179,107200.0,INLAND
10316,-121.53,39.19,27.0,2080.0,412.0,1082.0,382.0,2.5495,98300.0,INLAND
10317,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
10318,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
10319,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

#  SPECIFIC RANGE NO OF ROWS

In [79]:
data7=pd.read_csv("housing.csv",nrows=500)
data7

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
495,-122.25,37.86,52.0,4048.0,663.0,1316.0,590.0,5.3794,376900.0,NEAR BAY
496,-122.26,37.85,52.0,3618.0,768.0,1508.0,755.0,3.2619,309600.0,NEAR BAY
497,-122.27,37.85,52.0,4076.0,920.0,1800.0,815.0,2.7054,182300.0,NEAR BAY
498,-122.27,37.85,47.0,2077.0,400.0,719.0,326.0,2.2431,172700.0,NEAR BAY
499,-122.27,37.85,50.0,1279.0,300.0,675.0,255.0,1.9028,150800.0,NEAR BAY

# ERRORS

## encoding == uft-8 formate using their own data set uft formate   encoding= "latin-1" 

## bad line remove the extra columns /val    error_bad_lines=False

# DATA TYPE PARMETER AND ITS CONVERSIONN

In [81]:
data7=pd.read_csv("housing.csv",nrows=500)
data7.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           500 non-null    float64
 1   latitude            500 non-null    float64
 2   housing_median_age  500 non-null    float64
 3   total_rooms         500 non-null    float64
 4   total_bedrooms      498 non-null    float64
 5   population          500 non-null    float64
 6   households          500 non-null    float64
 7   median_income       500 non-null    float64
 8   median_house_value  500 non-null    float64
 9   ocean_proximity     500 non-null    str
dtypes: float64(9), str(1)
memory usage: 43.1 KB

In [89]:
data7=pd.read_csv("housing.csv",nrows=500,dtype={'total_rooms':int})
data7.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           500 non-null    float64
 1   latitude            500 non-null    float64
 2   housing_median_age  500 non-null    float64
 3   total_rooms         500 non-null    int64
 4   total_bedrooms      498 non-null    float64
 5   population          500 non-null    float64
 6   households          500 non-null    float64
 7   median_income       500 non-null    float64
 8   median_house_value  500 non-null    float64
 9   ocean_proximity     500 non-null    str
dtypes: float64(8), int64(1), str(1)
memory usage: 43.1 KB

# RENAMING

In [90]:
def renname(name):
    if name == "NEAR BAY":
        return "yes located"
    else:
        return  name 
    

data7=pd.read_csv("housing.csv",nrows=500,converters={'ocean_proximity':renname})
data7

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,yes located
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,yes located
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,yes located
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,yes located
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,yes located
...,...,...,...,...,...,...,...,...,...,...
495,-122.25,37.86,52.0,4048.0,663.0,1316.0,590.0,5.3794,376900.0,yes located
496,-122.26,37.85,52.0,3618.0,768.0,1508.0,755.0,3.2619,309600.0,yes located
497,-122.27,37.85,52.0,4076.0,920.0,1800.0,815.0,2.7054,182300.0,yes located
498,-122.27,37.85,47.0,2077.0,400.0,719.0,326.0,2.2431,172700.0,yes located
499,-122.27,37.85,50.0,1279.0,300.0,675.0,255.0,1.9028,150800.0,yes located

# CHUNKING

In [91]:
DATA_CHUNKS=pd.read_csv("housing.csv",chunksize=5000)

In [93]:
for chunk in DATA_CHUNKS:
    print(chunk.size)

50000
50000
50000
50000
6400

# NA vals

In [102]:
pd.read_csv("student.csv")

   Student_ID     Name  Math_Score  Science_Score Attendance Status
0         101    Alice        85.0             90        95%   Pass
1         102      Bob         NaN             82        80%   Pass
2         103  Charlie        78.0             85        75%   Pass
3         104    David        92.0             77        90%   Pass
4         105      Eva         NaN             95        60%   Fail
5         106    Frank        88.0             89        85%   Pass

In [101]:
pd.read_csv("student.csv",na_values=['Pass'])

   Student_ID     Name  Math_Score  Science_Score Attendance Status
0         101    Alice        85.0             90        95%    NaN
1         102      Bob         NaN             82        80%    NaN
2         103  Charlie        78.0             85        75%    NaN
3         104    David        92.0             77        90%    NaN
4         105      Eva         NaN             95        60%   Fail
5         106    Frank        88.0             89        85%    NaN