In [1]:
import pandas as pd

In [6]:
data=pd.read_csv("housing.csv")

In [7]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [8]:
data.shape

(20640, 10)

In [12]:
data2=pd.read_csv("file.tsv")

data2

            0\t50\t5\t881250949
0          0\t172\t5\t881250949
1          0\t133\t1\t881250949
2        196\t242\t3\t881250949
3        186\t302\t3\t891717742
4         22\t377\t1\t878887116
...                         ...
99997    880\t476\t3\t880175444
99998    716\t204\t5\t879795543
99999   276\t1090\t1\t874795795
100000    13\t225\t2\t882399156
100001    12\t203\t3\t879959583

[100002 rows x 1 columns]

In [13]:
data2=pd.read_csv("file.tsv",sep="\t")

data2

          0    50  5  881250949
0         0   172  5  881250949
1         0   133  1  881250949
2       196   242  3  881250949
3       186   302  3  891717742
4        22   377  1  878887116
...     ...   ... ..        ...
99997   880   476  3  880175444
99998   716   204  5  879795543
99999   276  1090  1  874795795
100000   13   225  2  882399156
100001   12   203  3  879959583

[100002 rows x 4 columns]

In [14]:
data=pd.read_csv("housing.csv",nrows=500)

In [15]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
495,-122.25,37.86,52.0,4048.0,663.0,1316.0,590.0,5.3794,376900.0,NEAR BAY
496,-122.26,37.85,52.0,3618.0,768.0,1508.0,755.0,3.2619,309600.0,NEAR BAY
497,-122.27,37.85,52.0,4076.0,920.0,1800.0,815.0,2.7054,182300.0,NEAR BAY
498,-122.27,37.85,47.0,2077.0,400.0,719.0,326.0,2.2431,172700.0,NEAR BAY
499,-122.27,37.85,50.0,1279.0,300.0,675.0,255.0,1.9028,150800.0,NEAR BAY

In [17]:
data=pd.read_csv("housing.csv",nrows=500,usecols=["total_rooms","total_bedrooms","population","households"])

data

     total_rooms  total_bedrooms  population  households
0          880.0           129.0       322.0       126.0
1         7099.0          1106.0      2401.0      1138.0
2         1467.0           190.0       496.0       177.0
3         1274.0           235.0       558.0       219.0
4         1627.0           280.0       565.0       259.0
..           ...             ...         ...         ...
495       4048.0           663.0      1316.0       590.0
496       3618.0           768.0      1508.0       755.0
497       4076.0           920.0      1800.0       815.0
498       2077.0           400.0       719.0       326.0
499       1279.0           300.0       675.0       255.0

[500 rows x 4 columns]

In [21]:
## actuly remove the head

data=pd.read_csv("housing.csv",header=1)
data

,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
0,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
1,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
2,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
3,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
4,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20634,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20635,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20636,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20637,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20638,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [26]:
## if the data have the ext val in the line or row it should be remove by these 

data=pd.read_csv("housing.csv",on_bad_lines='skip')

In [27]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [28]:
data.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [40]:
data=pd.read_csv("housing.csv",dtype={'total_rooms':int})
data.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms             int64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [41]:
# parse_date

In [46]:
def rename(name):
    if name =="INLAND":
        return 0       
      


    return 1

In [47]:
data=pd.read_csv("housing.csv",converters={"ocean_proximity":rename})
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,1
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0

In [48]:
data=pd.read_csv("housing.csv",na_values=[17.0])
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,NaN,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [49]:
data=pd.read_csv("housing.csv",nrows=20000,chunksize=5000)
data

In [50]:
for i in data:
    print(i.shape)

(5000, 10)
(5000, 10)
(5000, 10)
(5000, 10)

In [52]:
data=pd.read_csv("housing.csv")

In [53]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [61]:
data=data.drop(['median_income'], axis=1)
data

,longitude,housing_median_age,total_bedrooms,median_house_value,ocean_proximity
0,-122.23,41.0,129.0,452600.0,NEAR BAY
1,-122.22,21.0,1106.0,358500.0,NEAR BAY
2,-122.24,52.0,190.0,352100.0,NEAR BAY
3,-122.25,52.0,235.0,341300.0,NEAR BAY
4,-122.25,52.0,280.0,342200.0,NEAR BAY
...,...,...,...,...,...
20635,-121.09,25.0,374.0,78100.0,INLAND
20636,-121.21,18.0,150.0,77100.0,INLAND
20637,-121.22,17.0,485.0,92300.0,INLAND
20638,-121.32,18.0,409.0,84700.0,INLAND
20639,-121.24,16.0,616.0,89400.0,INLAND

In [55]:
data=data.drop(columns=["total_rooms","population"])

In [56]:
data

,longitude,latitude,housing_median_age,total_bedrooms,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,129.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,1106.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,190.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,235.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,280.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,374.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,150.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,485.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,409.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,616.0,530.0,2.3886,89400.0,INLAND

In [62]:
data=data.drop_duplicates()

In [63]:
data

,longitude,housing_median_age,total_bedrooms,median_house_value,ocean_proximity
0,-122.23,41.0,129.0,452600.0,NEAR BAY
1,-122.22,21.0,1106.0,358500.0,NEAR BAY
2,-122.24,52.0,190.0,352100.0,NEAR BAY
3,-122.25,52.0,235.0,341300.0,NEAR BAY
4,-122.25,52.0,280.0,342200.0,NEAR BAY
...,...,...,...,...,...
20635,-121.09,25.0,374.0,78100.0,INLAND
20636,-121.21,18.0,150.0,77100.0,INLAND
20637,-121.22,17.0,485.0,92300.0,INLAND
20638,-121.32,18.0,409.0,84700.0,INLAND
20639,-121.24,16.0,616.0,89400.0,INLAND

In [64]:
data=data.drop([1,6,8])

In [65]:
data

,longitude,housing_median_age,total_bedrooms,median_house_value,ocean_proximity
0,-122.23,41.0,129.0,452600.0,NEAR BAY
2,-122.24,52.0,190.0,352100.0,NEAR BAY
3,-122.25,52.0,235.0,341300.0,NEAR BAY
4,-122.25,52.0,280.0,342200.0,NEAR BAY
5,-122.25,52.0,213.0,269700.0,NEAR BAY
...,...,...,...,...,...
20635,-121.09,25.0,374.0,78100.0,INLAND
20636,-121.21,18.0,150.0,77100.0,INLAND
20637,-121.22,17.0,485.0,92300.0,INLAND
20638,-121.32,18.0,409.0,84700.0,INLAND
20639,-121.24,16.0,616.0,89400.0,INLAND

In [67]:
data=data.drop(index=[0,2,3])
data

,longitude,housing_median_age,total_bedrooms,median_house_value,ocean_proximity
4,-122.25,52.0,280.0,342200.0,NEAR BAY
5,-122.25,52.0,213.0,269700.0,NEAR BAY
7,-122.25,52.0,687.0,241400.0,NEAR BAY
9,-122.25,52.0,707.0,261100.0,NEAR BAY
10,-122.26,52.0,434.0,281500.0,NEAR BAY
...,...,...,...,...,...
20635,-121.09,25.0,374.0,78100.0,INLAND
20636,-121.21,18.0,150.0,77100.0,INLAND
20637,-121.22,17.0,485.0,92300.0,INLAND
20638,-121.32,18.0,409.0,84700.0,INLAND
20639,-121.24,16.0,616.0,89400.0,INLAND

In [70]:
data=data.dropna() ## will drop those rows which have 1 blank row
data

,longitude,housing_median_age,total_bedrooms,median_house_value,ocean_proximity
4,-122.25,52.0,280.0,342200.0,NEAR BAY
5,-122.25,52.0,213.0,269700.0,NEAR BAY
7,-122.25,52.0,687.0,241400.0,NEAR BAY
9,-122.25,52.0,707.0,261100.0,NEAR BAY
10,-122.26,52.0,434.0,281500.0,NEAR BAY
...,...,...,...,...,...
20635,-121.09,25.0,374.0,78100.0,INLAND
20636,-121.21,18.0,150.0,77100.0,INLAND
20637,-121.22,17.0,485.0,92300.0,INLAND
20638,-121.32,18.0,409.0,84700.0,INLAND
20639,-121.24,16.0,616.0,89400.0,INLAND

In [77]:
data=pd.read_csv("housing.csv")

In [78]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [83]:
data=data.dropna(subset=["housing_median_age","total_rooms","total_bedrooms"],how='any')
# id the you find any row and then have the empty cell then drop 
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [108]:
data=pd.read_csv("housing.csv")
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [82]:
data=data.dropna(subset=["housing_median_age","total_rooms","total_bedrooms"],how='all')
# if 3 have have blank cell in single row drop that so not found 
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [85]:
data=data.drop(data[data['total_rooms']<100].index)
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [88]:
data=data.fillna(0)
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [90]:
modee=data["housing_median_age"].mean()
modee

np.float64(28.627473920249585)

In [111]:
# This removes leading/trailing spaces from all column names

# Now try your line again
data['total_rooms'] = data[data['total_rooms']].fillna(data['total_rooms'].median())
data

KeyError: "None of [Index([ 880.0, 7099.0, 1467.0, 1274.0, 1627.0,  919.0, 2535.0, 3104.0, 2555.0,\n       3549.0,\n       ...\n       2640.0, 2655.0, 2319.0, 2080.0, 2332.0, 1665.0,  697.0, 2254.0, 1860.0,\n       2785.0],\n      dtype='float64', length=20640)] are in the [columns]"

In [112]:
# Just call .fillna() directly on the column series
data['total_rooms'] = data['total_rooms'].fillna(data['total_rooms'].median())

# Check if it worked
print(data['total_rooms'].isnull().sum())

0

In [113]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND